### ISSUE TITLE
Installation: make fails

### ISSUE THREAD

**Issue by chrisranderson** [ethanhowell/vowels#1]
Ubuntu 16.04
gcc 4.9.3
make 4.1

```
~/bin/vowels
🎸 : make
gcc -c -ansi -O2 -march=native -s -o obj/error.o src/error.c -Iinclude
Assembler messages:
Fatal error: can't create obj/error.o: No such file or directory
Makefile:31: recipe for target 'obj/error.o' failed
make: *** [obj/error.o] Error 1

~/bin/vowels
🎸 : 
```

**Comment by ethanhowell** [comment]
Thanks for reporting that bug! The problem was that the `obj` directory was not already created, so `make` did not create it as intended. It works now

**Comment by chrisranderson** [comment]
Yep, I can now run a hello world example. It might be nice to add an example program to the README.
