### ISSUE TITLE
Maybe add comments?

### ISSUE THREAD

**Issue by chrisranderson** [ethanhowell/vowels#2]
It would be nice to add explanatory comments to demos / my own code. Or maybe that's just totally against the idea of a language like this.

**Comment by ethanhowell** [comment]
Yeah the best way to comment would be to use something that looked like the English vowels. The program can handle up to [ISO Latin](https://en.wikipedia.org/wiki/ISO/IEC_8859-1) no problem, so the easiest thing to do would be something like:
```
Thïs ïs thë Hëllö Wörld prögräm ïn Vöwëls:
ueyeouoeueaeuaieuaieuoaeaiueaaoeiooeuoaeuoueuaieueeeaaieeoeeeeey
```
It is an esoteric language, so programming in it (and adding comments) is meant to be a pain
