### ISSUE TITLE
Suggestion: add mini-demos under each language feature

### ISSUE THREAD

**Issue by chrisranderson** [ethanhowell/vowels#3]
E.g.

#### Addition

*Syntax: `[arithmetic][addition][stack]`*

The vowel a marks an addition command. This command pops the top 2 elements off the destination stack, adds them, stores any overflow in the Overflow Status Register, and pushes the sum back to the stack.

```
# Stack A: 1, 3, 4, 5
aaa
# Stack A: 4, 4, 5
```

**Comment by chrisranderson** [comment]
Also, a suggestion for the syntax part: since there's only one option for `[arithmetic]` and `[addition]`, maybe just put `aa[stack]`.

**Comment by ethanhowell** [comment]
@chrisranderson  good idea, I'm working on it
