### ISSUE TITLE
Can't get echo program to work

### ISSUE THREAD

**Issue by chrisranderson** [ethanhowell/vowels#4]
File:
```
uaa
uea
y

```

My intent:
- Wait for me to enter a character, and put the ASCII value of that character on stack A.
- Print out the contents of the stack to the console.

However, nothing is printed:
![image](https://user-images.githubusercontent.com/5461398/28746461-174a7540-744a-11e7-9e18-c1471690ef65.png)

The "a" is what I input. I would expect the next line to display "a".

**Comment by ethanhowell** [comment]
There was an off by one error in the string-printing routine for stacks that caused nothing to be printed. It is fixed now
