### ISSUE TITLE
Write comprehensive tests

### ISSUE THREAD

**Issue by lwb4** [ethanhowell/vowels#5]
This project needs a comprehensive test suite. 

Attached is a description of all the tests we will need.

[Vowels, Comprehensive Tests.pdf](https://github.com/ethanhowell/vowels/files/1249565/Vowels.Comprehensive.Tests.pdf)

**Comment by lwb4** [comment]
Ensure that in addition, each test passes valgrind with no memory leaks.

**Comment by ethanhowell** [comment]
lol not currently worth the time
